### ISSUE TITLE
Query with provenance take hours to complete for large dataset 

### ISSUE THREAD

**Issue by xuanluolena** [PierreSenellart/provsql#27]
Hello!

I am trying to generate provenance with provsql for TPC-H queries with scale 1(8 tables, with up to 6 million records in one table).  However,  the following query costs 8 hours:
```sql
select
    l_returnflag,
    l_linestatus,
    sum(l_quantity) as sum_qty,
    sum(l_extendedprice) as sum_base_price,
    sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
    sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
    avg(l_quantity) as avg_qty,
    avg(l_extendedprice) as avg_price,
    avg(l_discount) as avg_disc,
    count(*) as count_order,
    formula(provenance(), 'provenance_mapping') as provenance
from
    lineitem
where
    l_shipdate <= date '1998-12-01' - interval '90' day
group by
    l_returnflag,
    l_linestatus
order by
    l_returnflag,
    l_linestatus
limit 1;
```

Also, I noticed that there are three parameters which seems have impact on the query performance:
provsql.max_nb_gates, provsql.init_nb_gates, provsql.avg_nb_wires. 
Do you mind sharing any best practice on tuning the value of them?

**Comment by PierreSenellart** [comment]
Thanks for your message. We are aware of this, at the moment ProvSQL is only really comfortably usable with small datasets. But we are working on this, and hope to have a satisfactory solution within a couple of months. Indeed, there is no reason provenance management on such a table would need to take that long, so there is definitely some serious optimization to be done. (We expect that provenance management should only cost a small constant factor wrt base querying.) We are also working with the TPC-H dataset, so we should be able to reproduce your setting quite faithfully.

`provsql.max_nb_gates`, `provsql.init_nb_gates`, `provsql.avg_nb_wires` control how much shared memory ProvSQL will use (`max_nb_gates` is the maximum number of gates in a provenance circuit; `init_nb_gates` the initial number of gates in the circuit; `avg_nb_wires` the average expected degree of circuit gates) – but this is also constrained by the amount of shared memory available to PostgreSQL, which by default is quite low (128MB I believe, see the `shared_buffers` variable of the PostgreSQL server). That being said, this should only be relevant if you exhaust the available memory, in which case you would get an error “Too many gates in in-memory circuit”. If you don't get this error, you are not reaching this limit. (And we are also working at the moment on gracefully handling the case where you reach the shared memory limit by using disk storage.) Arguably, setting init_nb_gates to be the same as max_nb_gates may improve performance a bit, but I don't think it will have much of an impact.

I will update this issue if we manage to cut down on the running time. Of course, we also welcome contributions/collaborations on this!

**Comment by PierreSenellart** [comment]
I'm actually only just now realizing (sorry for not seeing this before) that your query involves aggregation, and actually involves many aggregation operators. Though ProvSQL supports some form of terminal aggregation to produce semi-module aggregation values, this is quite inefficient by nature due to the way aggregation semi-modules are designed.

See http://delta-apache-vm.cs.tau.ac.il/~danielde/publications/pods2011b.pdf for the description of the way provenance of aggregates is handled. There is not much hope in this being efficient, as provenance of aggregate functions need to capture the possibility for every tuple to be present or absent, which has a dramatic effect on aggregates. It is unclear whether there is a better way of handling this without losing expressiveness.

Though we will continue working on the efficiency of ProvSQL for non-aggregate queries (and I think there is still a lot to be gained here), efficiency of aggregate queries is neither a priority nor even something that might be realistically done in all generality.

**Comment by xuanluolena** [comment]
Hey Pierre,

I see. Thank you so much for the update. 

Regards,
Xuan
